version: "3.7"

services:
  app:
    container_name: ${APP_NAME}
    platform: linux/amd64
    build: .
    links:
      - db
    ports:
      - "${EXTERNAL_APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /usr/share/billing_app/:/app/in
  db:
    container_name: ${DB_NAME}
    platform: linux/amd64
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: billdb
      MYSQL_USER: billdb_owner
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
