version: "3.7"

services:
  app:
    container_name: "${APP_NAME:-billing_app}"
    platform: linux/amd64
    build: .
    ports:
      - "${EXIT_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "${PATH_APP}/in/:/home/app_user/in"
  db:
    container_name: "${DB_NAME:-billing_db}"
    platform: linux/amd64
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: billdb
      MYSQL_USER: billdb_owner
      MYSQL_PASSWORD: password
    volumes:
      - "${PATH_APP}/db:/docker-entrypoint-initdb.d/"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
