version: "2"
services:
  app:
    container_name: ${APP_NAME}
    restart: always
    platform: "linux/amd64"
    build: ./weightApp
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "${EXIT_PORT}:8081"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: weight
    volumes:
      - ./in:/in
  db:
    container_name: ${DB_NAME}
    platform: "linux/amd64"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_DATABASE: weight
      MYSQL_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - mydb1:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
volumes:
  - mydb1:
